CREATE TABLE sell_order (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sell_order_number VARCHAR(50) NOT NULL UNIQUE,
    po_id INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (po_id) REFERENCES po_main(id)
);
